### ISSUE TITLE
Handle rate limit 429 response from API provider

### ISSUE THREAD

**Issue by heronimus** [asiantbd/crypto-discord-bot#55]
**Describe the bug**
The 429 Response (rate-limited) from the API provider (such as coingecko) isn't handled properly and caused the bot to panic:
```
main_test.go:94: Core.IDMapper() error = failed to map id: {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}, wantErr false
```

**Expected behavior**
Handled by logging warn/err or have retries countdown.

**Additional context**

**Comment by joshuagibeonm** [comment]
Fixed at #86
